# Site settings
title: Digital Scholarship Resources - Vanderbilt Libraries Digital Scholarship and Communications Office
description: Provided by the Vanderbilt Libraries Digital Scholarship and Communications Office
url: "https://heardlibrary.github.io"
baseurl: "/digital-scholarship"
theme: jekyll-theme-leap-day
# disables code block syntax highlighting
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true