# Site settings
title: Digital Scholarship Resources - Vanderbilt Libraries Digital Scholarship and Scholarly Communications Office
description: Provided by the Vanderbilt Libraries Digital Scholarship and Scholarly Communications Office
url: "https://heardlibrary.github.io"
baseurl: "/digital-scholarship"
theme: jekyll-theme-leap-day
