# Site settings
title: Digital Education Resources - Vanderbilt Libraries Digital Lab
description: Provided by the Vanderbilt Heard Libraries Digital Lab
url: "https://heardlibrary.github.io"
baseurl: "/digital-scholarship"
theme: jekyll-theme-leap-day
# disables code block syntax highlighting
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true