collection_json_filename: ww1_posters.json
collection_label: World War I Propaganda Posters
collection_summary: A collection of prints by unknown American artists.
attribution: Provided by Vanderbilt University Art Gallery
